// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Curry from "rescript/lib/es6/curry.js";
import * as React from "react";
import * as ReactI18next from "react-i18next";
import * as ProfileMenuJs from "./ProfileMenu.js";

var make = ProfileMenuJs.ProfileMenu;

var ProfileMenu = {
  make: make
};

function JuryAnalytics(Props) {
  var match = ReactI18next.useTranslation("namespace1");
  var t;
  if (match.length !== 3) {
    t = (function (a) {
        return a;
      });
  } else {
    var t$1 = match[0];
    t = (function (a) {
        return Curry._2(t$1, a, a);
      });
  }
  return React.createElement("div", {
              className: "container flex justify-center flex-1 bg-brown-dark2 text-semi-bright"
            }, React.createElement("div", {
                  className: "relative flex justify-center flex-1"
                }, React.createElement("div", undefined, React.createElement("div", {
                          className: "uppercase text-4xl text-semi-bright font-header text-center mt-32"
                        }, Curry._1(t, "jury-analytics")))), React.createElement(make, {}));
}

var make$1 = JuryAnalytics;

export {
  ProfileMenu ,
  make$1 as make,
  
}
/* make Not a pure module */
