name: Node CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Install Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '14.x'
    - name: Deploy to Server
      uses: easingthemes/ssh-deploy@main
      env:
        SSH_PRIVATE_KEY:  ${{ secrets.SSH_KEY }}
        # Remote host
        REMOTE_HOST: ${{ secrets.HOST }}
        # Remote user
        REMOTE_USER: ${{ secrets.USERNAME }}
        # Remote port
        REMOTE_PORT: ${{ secrets.PORT }}
        # Source directory
        SOURCE: # optional, default is 
        # Target directory
        TARGET: ${{ secrets.TARGET }}
        # Arguments to pass to rsync
        ARGS: # optional, default is -rltgoDzvO
        # An array of folder to exclude
        EXCLUDE: "/react-client/build/, /node_modules/"
    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.SSH_KEY }}
        port: ${{ secrets.PORT }}
        script: /bin/sh /var/www/photo-platform/go.sh
